Revert "Do not require a less specific type than what is really needed"
This reverts commit 4cdb76d84ea3c639a7fe241ccd9c18fae1e7ba96 as it
causes problems during XML inflation.

> android.view.InflateException: Binary XML file line #44:
> Error inflating class cgeo.geocaching.settings.CheckGcCredentialsPreference